baseURL: https://krustlet.dev/
languageCode: en-us
title: Krustlet
theme: clean-landing

disableKinds:
 -taxonomy
 -taxonomyTerm

params:
  description: Kubernetes Kubelet in Rust for running WASM
  openGraph: true
  twittersite: krustlet
  twittertype: summary_large_image
  twitterimage: images/krustlet-twitter-card.png
  font:
    name: "Varela Round"
    sizes: [400,600]
  navbar:
  - title: GitHub
    url: https://github.com/krustlet/krustlet
  - title: Docs
    url: https://docs.krustlet.dev
  - title: Blog
    url: https://deislabs.io/tags/krustlet/
  - title: Slack
    url: https://kubernetes.slack.com/messages/krustlet
  - title: Twitter
    url: https://twitter.com/krustlet
